#!/usr/bin/perl
#

use strict;

my $infl=shift(@ARGV);
# my $outfl=shift(@ARGV);
my $scheme=shift(@ARGV);

unless(open(XMLIN,"$infl"))
{
 die("File $infl not foind. Transformation failed.\n");
}

print <<HEADER;
<?xml version="1.0" encoding="UTF-8"?>
<!--
  This file was automaticly generated by ent2hrc
   http://info-esta.ru/efremov/colorer/index.html?intname=colorer.bin.ent2hrc
  (c) written by Eugene Efremov <4mirror\@mail.ru>
 -->
  <scheme name="$scheme">
   <keywords region="xml:CharRef" worddiv="[&amp;\\;]">
HEADER

while(<XMLIN>)
{
 if(/<!ENTITY\s+(\w+)\s+".+">/)
 {
  print "    <word name='$1'/>\n";
 }
}
close(XMLIN);

print <<FOOTER;
   </keywords>
  </scheme>
FOOTER
