name: Taged release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-schemes:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build schemes
        working-directory: ${{runner.workspace}}/Colorer-schemes
        run: ./build.sh base.distr-all ${{ github.ref_name }}

      - name: Create release
        run: gh release create ${{ github.ref_name }} ./_build/*.zip -t "Colorer base ${{ github.ref_name }}" -n "new version"
        env:
          GITHUB_TOKEN: ${{secrets.PACKAGES_GITHUB_TOKEN}}
